import random
import turtle
turtle.bgcolor('black')
turtle.speed(-0)
turtle.width(1)
paint=(['blue','light blue','dark blue'])
while True:
    turtle.goto(0,-300)
    angle=random.randint(0,180)
    length=random.randint(150,600)
    turtle.color(random.choice(paint))
    turtle.seth(angle)
    turtle.fd(length)
    turtle.goto(0, -300)
    angle = random.randint(0, 180)
    length = random.randint(150, 600)
    turtle.color(random.choice(paint))
    turtle.seth(angle)
    turtle.fd(length)
    turtle.goto(0, -300)
    angle = random.randint(0, 180)
    length = random.randint(150, 600)
    turtle.color(random.choice(paint))
    turtle.seth(angle)
    turtle.fd(length)
    turtle.goto(0, -300)
    angle = random.randint(0, 180)
    length = random.randint(150, 600)
    turtle.color(random.choice(paint))
    turtle.seth(angle)
    turtle.fd(length)
